version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always
    hostname: challenge

  tests:
    build:
      context: .
    command: npm test
    depends_on:
      - selenium
